envs:
  - id: Acrobot
    version: 0
    entry_point: envs:AcrobotEnv
    timestep_limit: 500
    description: |
      The acrobot system includes two joints and two links, where the joint between the two links is actuated.
      Initially, the links are hanging downwards, and the goal is to swing the end of the lower link
      up to a given height.
    requirements:
      - gym
      - numpy
    files:
      - envs/__init__.py
      - envs/acrobot.py
      - envs/assets/clockwise.png
    commit_hash: master

  - id: CartPole
    version: 0
    entry_point: envs:CartPoleEnv
    timestep_limit: 200
    reward_threshold: 195.0
    requirements:
      - gym
      - math
      - numpy
    files:
      - envs/__init__.py
      - envs/cartpole.py
      - envs/assets/clockwise.png
    commit_hash: master

  - id: CartPole
    version: 1
    entry_point: envs:CartPoleEnv
    timestep_limit: 500
    reward_threshold: 475.0
    requirements:
      - gym
      - math
      - numpy
    files:
      - envs/__init__.py
      - envs/cartpole.py
      - envs/assets/clockwise.png
    commit_hash: master

